[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
todo_app = "6yqnmGWqYe159aJsA6RKxYHQ2arhuTLJJ8D6QTH3dYK"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/longtran/.config/solana/id.json"

[scripts]
# test = "npx ts-mocha tests/**/create-profile.ts"
# test = "npx ts-mocha tests/**/create-todo.ts"
test = "npx ts-mocha tests/**/toggle-todo.ts"

