[toolchain]
anchor_version = "0.30.0"

[features]
seeds = false
skip-lint = false

[programs.devnet]
stake_program = "A9xJfDKFcjnunzqvQxr6UA6CmC3DnrQP6yB59MJ6sC7y"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/longtran/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/stake-program.ts"
